name: Demo

on:
  pull_request:
    types: [labeled, synchronize, edited]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: copapow/javascript-action-example@main
        id: bump
        with:
          path: 'sample-path'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ steps.bump.outputs.previous_version }} & ${{ steps.bump.outputs.new_version }}"
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'Bump package version'
