name: Demo

on:
  pull_request:
    types: [labeled, synchronize, edited]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: copapow/javascript-action-example@main
        with:
          path: 'sample-path'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: EndBug/add-and-commit@v7
