name: Bump Package Version On Merge

on:
  push:
    branches:
        - main

jobs:
  bump-package-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: copapow/javascript-action-example@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'Bump package version'