name: Demo

on:
  pull_request:
    types: [labeled, synchronize, edited]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: copapow/javascript-action-example@main
        with:
          path: 'sample-path'
          major_label: 'version-major'
          minor_label: 'version-minor'
          patch_label: 'version-patch'
          github_token: ${{ secrets.GITHUB_TOKEN }}
